student: content.cpp editor.cpp student.cpp ../Student/student.cpp ../InstructorMarksList/instructor_marks_list.cpp
	g++ content.cpp editor.cpp student.cpp ../Student/student.cpp ../InstructorMarksList/instructor_marks_list.cpp -o student

instructor: content.cpp editor.cpp instructor.cpp ../InstructorMarksList/instructor_marks_list.cpp
	g++ content.cpp editor.cpp instructor.cpp ../InstructorMarksList/instructor_marks_list.cpp -o instructor

hod: content.cpp editor.cpp hod.cpp ./../WorkingOfHOD/hod.cpp ./../InstructorMarksList/instructor_marks_list.cpp 
	g++ content.cpp editor.cpp hod.cpp ./../WorkingOfHOD/hod.cpp ./../InstructorMarksList/instructor_marks_list.cpp -o hod

admin: content.cpp editor.cpp admin.cpp adminHelper.cpp
	g++ content.cpp editor.cpp admin.cpp adminHelper.cpp -o admin
